name: Compile check

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --manifest-path open-msspe-design/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path open-msspe-design/Cargo.toml
